# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# copied from Matt Dray's blog https://www.rostrum.blog/2021/04/14/gha-readme/
on:
  push:
    branches:
      - master
  schedule:
    - cron: '09 05 * * *'

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 2
          extra-packages: |
            ggplot2
            rcmdcheck
          needs: |
            website
            coverage
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install CRAN packages
        run: Rscript -e 'pak::pkg_install(c("remotes", "rmarkdown", "knitr", "tidyverse", "xml2", "lubridate", "distill"))'
      - name: Render README
        run: Rscript -e 'knitr::knit("README.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit README.md README_files/ -m 'Re-build README.Rmd' || echo "No changes to commit"
           git push origin || echo "No changes to commit"

      